languageCode = "zh-cn"
languageName = "简体中文"
weight = 4
title = "Someijam"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "imgs/titlelogo.svg"
  description = "Someijam's Blog"
  copyright = "© { year }  Someijam [萌ICP备20230407号](https://icp.gov.moe/?keyword=20230407) "

[params.author]
  name = "Someijam"
  image = "imgs/202409072221634.jpg"
  # headline = "Someijam's Blog"
  bio = "墨香留痕思深意，字里行间见真知。阅文易有雅兴至，愿君难得赞评离。"
  links = [
    { github = "https://github.com/Someijam" },
    { youtube = "https://space.bilibili.com/1545394173" },
    { steam = "https://steamcommunity.com/profiles/76561199048294697/" },
  ]
